[package]
name = "sparse"
version = "0.1.0"
edition = "2021"


[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "sparse1"
harness = false
